# Conceptual Office Hours 1

## Importing 

In [7]:
from datascience import *
import numpy as np

## np.arange

### Case 1

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Case 2

In [9]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

### Case 3

In [10]:
np.arange(2,10,2)

array([2, 4, 6, 8])

## Creating Tables

In [11]:
fruit = Table().with_columns("Food", make_array("apple", "orange", "apple", "bannana"),
                             "Cost", make_array(3, 6, 5, 8),
                             "Store", make_array("Vons", "Costco", "Ralphs", "Vons"))
fruit # jeez, $8 for a bannana 

Food    | Cost | Store
apple   | 3    | Vons
orange  | 6    | Costco
apple   | 5    | Ralphs
bannana | 8    | Vons

## Relabeling 

Remember the difference between relabeled and relabel !!!!!

In [28]:
fruit.relabeled("Cost", "Cost ($)") # relabeled is recommended

Food    | Cost ($) | Store
apple   | 3        | Vons
orange  | 6        | Costco
apple   | 5        | Ralphs
bannana | 8        | Vons

## Adding a Column

In [13]:
new_costs = fruit.column("Cost") * 2
new_costs

array([ 6, 12, 10, 16])

In [14]:
fruit.with_columns("New Cost", new_costs)

Food    | Cost | Store  | New Cost
apple   | 3    | Vons   | 6
orange  | 6    | Costco | 12
apple   | 5    | Ralphs | 10
bannana | 8    | Vons   | 16

Note below that the fruit table is unchanged, that is because we did not change the fruit table in the cell above, only added a column to a new copy of the fruit table. If you want to change the original table you have to set it equal to the new copy: ```fruit = fruit.with_columns("New Cost", new_costs)```

In [29]:
fruit

Food    | Cost | Store
apple   | 3    | Vons
orange  | 6    | Costco
apple   | 5    | Ralphs
bannana | 8    | Vons

## Arrays can do element-wise math

In [15]:
make_array(1,2,3) + 1

array([2, 3, 4])

In [31]:
make_array(1,2,3) * 2

array([2, 4, 6])

In [32]:
make_array(1,2,3)**2

array([1, 4, 9])

## .where

In [16]:
fruit.where("Cost", 5)

Food  | Cost | Store
apple | 5    | Ralphs

In [17]:
fruit.where("Cost", are.below_or_equal_to(5))

Food  | Cost | Store
apple | 3    | Vons
apple | 5    | Ralphs

In [18]:
fruit.where("Store", "Vons")

Food    | Cost | Store
apple   | 3    | Vons
bannana | 8    | Vons

In [19]:
fruit.where("Store", are.not_containing("a")) 

Food    | Cost | Store
apple   | 3    | Vons
orange  | 6    | Costco
bannana | 8    | Vons

## .select vs .column

In [21]:
fruit.column("Cost") # Array

array([3, 6, 5, 8])

In [22]:
fruit.select("Cost") # Table

Cost
3
6
5
8

In [23]:
fruit.select("Food", "Cost") # select can take many columns

Food    | Cost
apple   | 3
orange  | 6
apple   | 5
bannana | 8

## Can also use indicies

(Column names are more readable though!)

In [25]:
fruit.select(0,1) # Same as fruit.select("Food", "Cost")

Food    | Cost
apple   | 3
orange  | 6
apple   | 5
bannana | 8

In [26]:
fruit.where(1, 5) # Same as fruit.where("Cost", 5)

Food  | Cost | Store
apple | 5    | Ralphs